In [5]:
import sys
# sys.path.append(r'C:\Users\edwar\Documents\LabStuff\ibllib\brainbox\io')
#sys.path.append(r'C:\Users\IBL\Documents\ibl_analysis\ONE\one')
import matplotlib.pyplot as plt
import numpy as np
from brainbox.io.one import load_wheel_reaction_times
import brainbox.behavior.wheel as wh
from ibllib.io.raw_data_loaders import *
from ibllib.pipes.tasks import *
from ibllib.pipes import *
from ibllib.io.extractors.bpod_trials import *
from one.api import ONE
from one.alf.io import *

from ibllib.io.extractors.ephys_fpga import extract_wheel_moves
from ibllib.io.extractors.training_wheel import extract_first_movement_times
#from localAlf import load_wheel_reaction_times_local
from brainbox.behavior.training import *

from ScanImageTiffReader import ScanImageTiffReader
import json
import ast

In [6]:
session_path = r'Z:\TM_Lab\Edward\Data\iblrig_data\Subjects\_iblrig_test_mouse\2024-03-05\009'
try:
    temp_trial_data = load_object(session_path+'\\alf', 'trials')
except:
    pass
trials, wheel, output_files = extract_all(session_path, save=True)

2024-03-05 13:00:58.643 INFO     [bpod_trials.py:61] Extracting Z:\TM_Lab\Edward\Data\iblrig_data\Subjects\_iblrig_test_mouse\2024-03-05\009 as habituation
2024-03-05 13:00:58.669 INFO     [bpod_trials.py:64] habituation session on _iblrig_TM_diesel_behavior
2024-03-05 13:00:58.670 WARNING  [habituation_trials.py:39] Z:\TM_Lab\Edward\Data\iblrig_data\Subjects\_iblrig_test_mouse\2024-03-05\009: Missing BNC1 TTLs on 1 trial(s)


c:\Users\dirk\anaconda3\envs\iblenv\lib\site-packages\ibllib\io\extractors\bpod_trials.py:58: FutureWarning: `extract_all` functions soon to be deprecated, use `bpod_trials.get_bpod_extractor` instead
  warnings.warn('`extract_all` functions soon to be deprecated, use `bpod_trials.get_bpod_extractor` instead', FutureWarning)


2024-03-05 13:00:58.918 INFO     [bpod_trials.py:101] session extracted 



In [7]:
trials

OrderedDict([('feedbackType',
              array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)),
             ('rewardVolume',
              array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])),
             ('stimOff_times',
              array([ 13.021499,  24.935699,  34.9549  ,  43.519299,  56.5045  ,
                      66.852899,  73.655   ,  87.219599,  97.9051  , 111.3699  ,
                     121.905199, 134.6368  , 143.5057  ])),
             ('contrastLeft',
              array([ 1., nan, nan, nan,  1.,  1., nan, nan,  1.,  1.,  1.,  1., nan])),
             ('contrastRight',
              array([nan,  1.,  1.,  1., nan, nan,  1.,  1., nan, nan, nan, nan,  1.])),
             ('feedback_times',
              array([ 11.8996  ,  23.800399,  33.822899,  42.4106  ,  55.284499,
                      65.7346  ,  72.525999,  86.0884  ,  96.761399, 110.2409  ,
                     120.7667  , 133.517099, 142.3743  ])),
             ('stimOn_times',
             

In [8]:
img_path = r'Z:\TM_Lab\Edward\Cerebellum_Imaging\test_ibl_sync_daq2p2_aux2_00001.tif'
reader=ScanImageTiffReader(img_path)
frames_metadata = []

with ScanImageTiffReader(img_path) as reader:
    num_frames = reader.shape()[0]  # Assuming the first dimension represents frames
    
    for i in range(num_frames):
        description = reader.description(i)
        frame_metadata = {}  # Dictionary to hold this frame's metadata
        
        for line in description.split('\n'):
            if '=' in line:  # Ensure there's a key-value pair to parse
                key, value = line.split('=', 1)  # Split by the first '='
                key = key.strip()
                
                try:
                    # Safely evaluate the value string to the appropriate Python data type
                    # This works for numbers, lists, dictionaries, etc.
                    value = ast.literal_eval(value.strip())
                except (ValueError, SyntaxError):
                    # If evaluation fails, keep the value as a string
                    value = value.strip()
                
                frame_metadata[key] = value
        
        frames_metadata.append(frame_metadata)
all_auxTrigger0 = []

# Iterate through each frame's metadata
for frame_metadata in frames_metadata:
    # Check if 'auxTrigger0' exists and is not empty
    if 'auxTrigger0' in frame_metadata and frame_metadata['auxTrigger0']:
        # Extend the all_auxTrigger0 list with the numbers from this frame's auxTrigger0
        all_auxTrigger0.extend(frame_metadata['auxTrigger0'])

In [18]:
frames_metadata

[{'frameNumbers': 1,
  'acquisitionNumbers': 1,
  'frameNumberAcquisition': 1,
  'frameTimestamps_sec': 0.0,
  'acqTriggerTimestamps_sec': -0.00011737,
  'nextFileMarkerTimestamps_sec': -1.0,
  'endOfAcquisition': 0,
  'endOfAcquisitionMode': 0,
  'dcOverVoltage': 0,
  'epoch': '[2024  3  5 12 25 15.238]',
  'auxTrigger0': [],
  'auxTrigger1': [],
  'auxTrigger2': [],
  'auxTrigger3': [],
  'I2CData': {}},
 {'frameNumbers': 2,
  'acquisitionNumbers': 1,
  'frameNumberAcquisition': 2,
  'frameTimestamps_sec': 0.06571506,
  'acqTriggerTimestamps_sec': -1.0,
  'nextFileMarkerTimestamps_sec': -1.0,
  'endOfAcquisition': 0,
  'endOfAcquisitionMode': 0,
  'dcOverVoltage': 0,
  'epoch': '[2024  3  5 12 25 15.238]',
  'auxTrigger0': [],
  'auxTrigger1': [],
  'auxTrigger2': [],
  'auxTrigger3': [],
  'I2CData': {}},
 {'frameNumbers': 3,
  'acquisitionNumbers': 1,
  'frameNumberAcquisition': 3,
  'frameTimestamps_sec': 0.13143023,
  'acqTriggerTimestamps_sec': -1.0,
  'nextFileMarkerTimestamps_

In [24]:
print(np.diff(all_auxTrigger0[0::2]))

[12.95676675 11.9115645  10.01545542  8.58164711 12.95767146 10.37415787
  6.77723928 13.58897666 10.66185833 13.49067591 10.51445768 12.75837133
  8.84284871 11.53836205]


In [25]:
print(np.diff(trials['goCueTrigger_times']))

[ 9.712899 11.9115   10.015401  8.581599 12.957601 10.374099  6.777201
 13.588899 10.661801 13.4906   10.514399 12.758301]
